### ISSUE TITLE
Work without steam

### ISSUE THREAD

**Issue by raulseixasbr** [Terrain2/Muck#1]
Do you have any idea on how make the multiplayer works without steam?
I could make it sync between players without steam, but when i chat it says id '0' was not in the dictionary.
players ids start in 1, so i dunno.

**Comment by sodiboo** [comment]
In general, the game doesn't really support non-Steam networking. Steamworks is quite integrated throughout the code, and even though the specific transport interface is abstracted away from Steam, it does still expose Steamworks types in that interface. You'd need to rewrite a bunch of the networking, which is not really difficult but it's tedious. You'd also need to create a proper UI for connecting to players which isn't inherently bound to Steam matchmaking.

Why would you want to run it without Steam though? The game is free, so... anyone can get it? And Steam's networking also proxies packets through Steam's relay servers, which prevents leaking the players' IP addresses, so it prevents certain attacks from that information.

And... what exactly did you do? You've modified the code to work without Steam, as is necessary, but you cannot debug an error or even provide the full error? Could i have a stacktrace so i can maybe help you figure out the issue?

**Comment by AlissonEgea** [comment]
To achieve a bugged multiplayer without steam, I firstly deactivated the steam lobby and steam manager and changed the Network controller to network type classic.
After that, i added the UiManager and NetworkManager scripts. With UiManager, I could add buttons to access the functions Host() and ConnectTest().
After the server is Hosted and The player is connected, I created another button that calls the function NetworkController.Instance.LoadGame();
When the GameAfterMenu scene is loaded, I called on the start method of the GameManager script the StartCoroutine(this.GenerateWorldRoutine());
The game is loaded, the player is spawned, and no errors are presented.
But when i try to say anything in chat, the following error appears and no message is displayed:


KeyNotFoundException: The given key '0' was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <e40e5a8f982c4b618a930d29f9bd091c>:0)
ChatBox.AppendMessage (System.Int32 fromUser, System.String message, System.String fromUsername, System.Boolean bypassLength) (at Assets/Scripts/Assembly-CSharp/ChatBox.cs:68)
ChatBox.SendMessage (System.String message) (at Assets/Scripts/Assembly-CSharp/ChatBox.cs:129)
ChatBox.UserInput () (at Assets/Scripts/Assembly-CSharp/ChatBox.cs:533)
ChatBox.Update () (at Assets/Scripts/Assembly-CSharp/ChatBox.cs:582)

**Comment by sodiboo** [comment]
If i recall correctly, the player IDs should start at 0, not at 1. The chat box would suggest so, because -1 is used for "no player", rather than 0 (which would make sense if players started at 1). It does seem like you've probably done something that prevents the client from properly registering that there are any players in this lobby, so when the server sends the chat message packet, the client just... doesn't know that player exists? Try debug logging the keys of ``GameManager.players`` right before the error occurs? (so like, between line 63 and 64 i guess)

**Comment by AlissonEgea** [comment]
There is only one Key/Value: Key: 1 - Value:Player (PlayerManager)
When I start the game, and Im in the loading screen, "MyId" changes to 1 in the LocalClient script.
Always starts in the id 1. The only changes I did was the ones I mentioned, the rest is totally the same as the repo

**Comment by AlissonEgea** [comment]
In the method InitializeServerData() we can see the following:
public static void InitializeServerData()
	{
		for (int i = 1; i <= Server.MaxPlayers; i++)
		{
			Server.clients.Add(i, new Client(i));
		}
		Server.InitializeServerPackets();
		Debug.Log("Initialized Packets.");
	}

The loop doesnt create the client in id 0

**Comment by AlissonEgea** [comment]
If I change the i = 0, to add the Client in id 0 the chat works but the player 0 isn't synchronized in multiplayer.
If I enter with 3 players, only player 2 (id 1) and 3 (id 2) can see moviment from each other.
